---
name: Build

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - master
  schedule:
    - cron: '00 03 * * *'

permissions:
  contents: read

env:
  DOCKERHUB_REPO_NAME: tuxdude/homelab-acme
  DOCKERHUB_TEST_TAG: ci-test
  DOCKERHUB_PUBLISH_TAG: ${{ github.ref_name }}

jobs:
  docker:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Export Build Args as Workflow Env vars
        run: ./build-args.sh >> $GITHUB_ENV

      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.DOCKERHUB_REPO_NAME }}:${{ env.DOCKERHUB_TEST_TAG }}
          build-args: |
            BASE_IMAGE_NAME=${{ env.BASE_IMAGE_NAME }}
            BASE_IMAGE_TAG=${{ env.BASE_IMAGE_TAG }}
            ACME_VERSION=${{ env.ACME_VERSION }}
            ACME_SHA256_CHECKSUM=${{ env.ACME_SHA256_CHECKSUM }}
            USER_NAME=${{ env.USER_NAME }}
            GROUP_NAME=${{ env.GROUP_NAME }}
            USER_ID=${{ env.USER_ID }}
            GROUP_ID=${{ env.GROUP_ID }}

      - name: Test
        run: |
          docker run --rm ${{ env.DOCKERHUB_REPO_NAME }}:${{ env.DOCKERHUB_TEST_TAG }} acme.sh --list

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKERHUB_REPO_NAME }}:${{ env.DOCKERHUB_PUBLISH_TAG }}
          build-args: |
            BASE_IMAGE_NAME=${{ env.BASE_IMAGE_NAME }}
            BASE_IMAGE_TAG=${{ env.BASE_IMAGE_TAG }}
            ACME_VERSION=${{ env.ACME_VERSION }}
            ACME_SHA256_CHECKSUM=${{ env.ACME_SHA256_CHECKSUM }}
            USER_NAME=${{ env.USER_NAME }}
            GROUP_NAME=${{ env.GROUP_NAME }}
            USER_ID=${{ env.USER_ID }}
            GROUP_ID=${{ env.GROUP_ID }}
